/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Check whether API process is live */
        readonly get: operations["getLiveHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get authenticated profile and authorization scope */
        readonly get: operations["getCurrentUser"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/providers": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List synthetic providers available in caller scope */
        readonly get: operations["listProviders"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/areas": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List synthetic areas available in caller scope */
        readonly get: operations["listAreas"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/outlets": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List synthetic outlets available in caller scope */
        readonly get: operations["listOutlets"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/ingestion/providers/{provider}/batches": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Ingest a checksum-verified synthetic provider feed batch
         * @description The `X-Provider-Ingest-Key` derives the provider scope and must match the path. Duplicate events are retained as feed-quality evidence and are never applied twice.
         */
        readonly post: operations["ingestProviderBatch"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/outlets/{id}/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get scoped outlet liquidity-health summary
         * @description Produces and persists a deterministic forecast run. `modelConfidence` measures analytical history coverage independently from feed `dataQuality`.
         */
        readonly get: operations["getOutletHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/outlets/{id}/balances": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get scoped, separate shared-cash and provider e-money positions
         * @description Shared cash and provider e-money are separate resources and are never exposed as a combined actionable balance.
         */
        readonly get: operations["getOutletBalances"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/outlets/{id}/forecasts": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Generate and persist a deterministic scoped liquidity forecast
         * @description Forecasts 30, 60, 120, and 240-minute bounds for shared cash and each authorized provider e-money resource. With `unreliable` quality, exact ETAs are null; the analytical confidence remains available.
         */
        readonly get: operations["getOutletForecasts"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/outlets/{id}/anomalies": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Generate and list deterministic unusual-activity review signals
         * @description Signals compare an outlet/provider evidence window with stored baseline activity. The response uses review-only language and never asserts fraud or causation. It may include a persisted correlation to separately retained shared-cash liquidity pressure.
         */
        readonly get: operations["listOutletAnomalies"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/outlets/{id}/data-quality": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List scoped active data-quality evidence for an outlet */
        readonly get: operations["getOutletDataQuality"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/outlets/{id}/transactions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List provider-scoped outlet ledger events */
        readonly get: operations["listOutletTransactions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/simulation/reset": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Reset deterministic synthetic simulation state
         * @description DEMO_ADMIN only. Restores seeded baseline balances and removes prior simulated feed receipts, events, snapshots, and quality incidents.
         */
        readonly post: operations["resetSimulation"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/simulation/start": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Reset and start deterministic scenario A, B, C, or D
         * @description DEMO_ADMIN only. Fixtures are submitted through the same ingestion validation and persistence path as provider batches.
         */
        readonly post: operations["startSimulation"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/simulation/step": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Apply the next deterministic scenario batch
         * @description DEMO_ADMIN only.
         */
        readonly post: operations["stepSimulation"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/alerts": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List review-only alerts in the verified caller's route scope
         * @description Provider alerts are visible only to routed provider members/assignments. Shared-cash alerts contain no competitor provider detail.
         */
        readonly get: operations["listAlerts"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/alerts/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get scoped alert evidence and localized message key */
        readonly get: operations["getAlert"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/alerts/{id}/acknowledge": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Acknowledge a scoped review alert
         * @description Review workflow only; this never changes a balance, ledger, provider feed, or financial state.
         */
        readonly post: operations["acknowledgeAlert"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/alerts/{id}/assign": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Assign a scoped alert to a routed recipient */
        readonly post: operations["assignAlert"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/alerts/{id}/create-case": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Create an idempotent, provider-scoped human-review case from an alert
         * @description Creates a review-only case and immutable creation/audit events. Requires a workflow role; it never changes a balance, ledger, provider feed, or financial state.
         */
        readonly post: operations["createAlertCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List provider-scoped review cases
         * @description Caller scope is derived from verified memberships, assignments, and alert routes; query filters can only narrow results.
         */
        readonly get: operations["listCases"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get one provider-scoped review case */
        readonly get: operations["getCase"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/timeline": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get immutable scoped case events, notes, and audit timeline */
        readonly get: operations["getCaseTimeline"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/acknowledge": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Move OPEN case to ACKNOWLEDGED
         * @description Requires `version`, `Idempotency-Key`, a workflow role, and provider scope. Review-only: cannot mutate financial tables.
         */
        readonly post: operations["acknowledgeCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/assign": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Assign or reassign a case to an active scoped assignee */
        readonly post: operations["assignCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/notes": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Add an immutable scoped review note */
        readonly post: operations["addCaseNote"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/request-verification": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Move ACKNOWLEDGED case to INVESTIGATING and record a review request */
        readonly post: operations["requestCaseVerification"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/escalate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Move INVESTIGATING case to ESCALATED */
        readonly post: operations["escalateCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/disposition": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Record a review disposition without changing financial state */
        readonly post: operations["recordCaseDisposition"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/resolve": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Resolve an INVESTIGATING or ESCALATED case with an allowlisted review code */
        readonly post: operations["resolveCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/close": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Move RESOLVED case to CLOSED */
        readonly post: operations["closeCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cases/{id}/reopen": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Reopen a CLOSED case to OPEN, clearing its prior resolution */
        readonly post: operations["reopenCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/feed-health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List provider feed freshness and derived data quality in caller scope
         * @description Requires a verified JWT and provider membership. `providerId` and `outletId` are narrowing filters; outlet filtering derives quality only from incidents visible at that outlet. Cursor pagination is stable by receipt time and ID.
         */
        readonly get: operations["listFeedHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/data-quality/incidents": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List scoped feed data-quality incidents
         * @description Requires a verified JWT. Filters and cursor pagination only narrow RLS-authorized incidents; cross-provider IDs return no additional data.
         */
        readonly get: operations["listDataQualityIncidents"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/management/readiness": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get fixed, redacted platform readiness aggregate
         * @description Requires a verified JWT plus `PLATFORM_MANAGEMENT` or `DEMO_ADMIN` membership. Returns only aggregate counts and timestamps; it never exposes provider, outlet, transaction, balance, or incident details.
         */
        readonly get: operations["getManagementReadiness"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        readonly ProviderCode: "PROVIDER_A" | "PROVIDER_B" | "PROVIDER_C";
        readonly IngestionEvent: {
            /** @description BDT integer minor units */
            readonly amountMinor: number;
            readonly eventId: string;
            readonly eventVersion: number;
            readonly idempotencyKey: string;
            /** @enum {string} */
            readonly lifecycle: "PENDING" | "SETTLED" | "FAILED" | "REVERSED";
            /** Format: date-time */
            readonly occurredAt: string;
            readonly outletCode: string;
            /** Format: date-time */
            readonly receivedAt: string;
            /** @enum {string} */
            readonly type: "CASH_IN" | "CASH_OUT";
        };
        readonly BalanceSnapshot: {
            readonly amountMinor: number;
            /** Format: date-time */
            readonly observedAt: string;
            readonly outletCode: string;
            /** @enum {string} */
            readonly resource: "shared_cash" | "provider_efloat";
        };
        /** @description Checksum is SHA-256 of the recursively key-sorted JSON payload excluding `checksum`. */
        readonly IngestionBatch: {
            readonly checksum: string;
            readonly events: readonly components["schemas"]["IngestionEvent"][];
            /** Format: date-time */
            readonly receivedAt: string;
            readonly sequence: number;
            readonly snapshots: readonly components["schemas"]["BalanceSnapshot"][];
            /** Format: date-time */
            readonly sourceAt: string;
        };
        readonly IngestionReceipt: {
            readonly acceptedEvents: number;
            /** Format: uuid */
            readonly batchId: string;
            readonly duplicateEvents: number;
            readonly provider: components["schemas"]["ProviderCode"];
            /** @enum {string} */
            readonly qualityStatus: "healthy" | "degraded";
            readonly rejectedEvents: number;
            readonly sequence: string;
        };
        readonly SimulationCommand: {
            /** @enum {string} */
            readonly scenario: "A" | "B" | "C" | "D";
        };
        readonly LiveHealthResponse: {
            /** @constant */
            readonly service: "prohori-api";
            /** @constant */
            readonly status: "ok";
        };
        readonly Provider: {
            /** Format: uuid */
            readonly id: string;
            /** @enum {string} */
            readonly code: "PROVIDER_A" | "PROVIDER_B" | "PROVIDER_C";
            readonly name: string;
            /** @enum {string} */
            readonly status: "ACTIVE" | "INACTIVE";
        };
        readonly Area: {
            /** Format: uuid */
            readonly id: string;
            readonly code: string;
            readonly name: string;
            /** Format: uuid */
            readonly parentId?: string | null;
        };
        readonly Outlet: {
            /** Format: uuid */
            readonly id: string;
            readonly code: string;
            readonly name: string;
            readonly area: components["schemas"]["Area"];
            readonly tier: number;
            readonly timezone: string;
            /** @enum {string} */
            readonly status: "ACTIVE" | "INACTIVE";
        };
        /** @description Implemented with verified Supabase identity in Step 3. */
        readonly CurrentUser: {
            /** Format: uuid */
            readonly id: string;
            /** @enum {string} */
            readonly locale: "en" | "bn";
            readonly memberships: readonly Record<string, never>[];
            readonly assignments: readonly Record<string, never>[];
        };
        readonly OutletHealth: {
            /** Format: uuid */
            readonly outletId: string;
            /** Format: uuid */
            readonly forecastRunId: string;
            /** @enum {string} */
            readonly dataQuality: "healthy" | "degraded" | "unreliable";
            readonly modelConfidence: number;
            readonly limitingResource: components["schemas"]["LimitingResource"];
            readonly unusualActivity?: readonly components["schemas"]["AnomalySignal"][];
        };
        readonly OutletBalances: {
            /** Format: uuid */
            readonly outletId: string;
            readonly sharedCash: components["schemas"]["ResourceBalance"];
            readonly providerEMoney: readonly components["schemas"]["ProviderResourceBalance"][];
        };
        readonly ResourceBalance: {
            /** @enum {string} */
            readonly resource: "shared_cash" | "provider_efloat";
            /** @description Integer BDT minor units serialized as a string */
            readonly amountMinor: string;
        };
        readonly ProviderResourceBalance: components["schemas"]["ResourceBalance"] & {
            readonly provider: components["schemas"]["Provider"];
        };
        readonly LimitingResource: {
            /** @enum {string} */
            readonly resource?: "shared_cash" | "provider_efloat";
            /** Format: uuid */
            readonly providerId?: string | null;
        } | null;
        readonly ForecastPoint: {
            /** @enum {integer} */
            readonly horizonMinutes: 30 | 60 | 120 | 240;
            readonly projectedLowMinor: string;
            readonly projectedMidMinor: string;
            readonly projectedHighMinor: string;
            /** @enum {string} */
            readonly riskBand: "low" | "moderate" | "high" | "critical";
            readonly reserveEtaMinutes: number | null;
            readonly likelyDepletionEtaMinutes: number | null;
        };
        readonly ForecastResource: {
            /** @enum {string} */
            readonly resource: "shared_cash" | "provider_efloat";
            /** Format: uuid */
            readonly providerId: string | null;
            readonly currentMinor: string;
            readonly demandRateMinorPerMinute: number;
            readonly points: readonly components["schemas"]["ForecastPoint"][];
        };
        readonly ForecastRun: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly outletId: string;
            /** Format: date-time */
            readonly generatedAt: string;
            /** @enum {string} */
            readonly dataQuality: "healthy" | "degraded" | "unreliable";
            readonly modelConfidence: number;
            readonly limitingResource: components["schemas"]["LimitingResource"];
            readonly resources: readonly components["schemas"]["ForecastResource"][];
        };
        readonly AnomalySignal: {
            /** Format: uuid */
            readonly id: string;
            /** @constant */
            readonly message: "Unusual activity requires review.";
            /** @enum {string} */
            readonly detectorType: "repeated_amount" | "abnormal_velocity";
            readonly detectorVersion: string;
            readonly observedValue: number;
            readonly baselineValue: number;
            readonly threshold: number;
            readonly score: number;
            readonly sourceTransactionIds: readonly string[];
            readonly evidenceWindow: {
                /** Format: date-time */
                readonly start: string;
                /** Format: date-time */
                readonly end: string;
            };
            readonly possibleBenignExplanation: string;
            readonly modelConfidence: number;
            /** @enum {string} */
            readonly dataQuality: "healthy" | "degraded" | "unreliable";
            readonly provider: components["schemas"]["Provider"];
            readonly correlation: {
                readonly score?: number;
                readonly threshold?: number;
                readonly context?: string;
            } | null;
        };
        readonly OutletDataQuality: {
            /** Format: uuid */
            readonly outletId: string;
            /** @enum {string} */
            readonly dataQuality: "healthy" | "degraded" | "unreliable";
            readonly incidents: readonly {
                /** Format: uuid */
                readonly id: string;
                readonly category: string;
                readonly details: Record<string, never>;
                /** Format: date-time */
                readonly detectedAt: string;
                /** Format: uuid */
                readonly providerId: string | null;
            }[];
        };
        readonly TransactionPage: {
            readonly items: readonly {
                /** Format: uuid */
                readonly id: string;
                readonly provider: components["schemas"]["Provider"];
                readonly amountMinor: string;
                /** @enum {string} */
                readonly type: "CASH_IN" | "CASH_OUT";
                /** @enum {string} */
                readonly lifecycle: "PENDING" | "SETTLED" | "FAILED" | "REVERSED";
                /** Format: date-time */
                readonly occurredAt: string;
            }[];
            /** Format: uuid */
            readonly nextCursor: string | null;
        };
        /** @enum {string} */
        readonly AlertType: "provider_emoney_pressure" | "shared_cash_pressure" | "unusual_activity_review" | "data_quality_issue" | "combined_review";
        /** @enum {string} */
        readonly CaseState: "OPEN" | "ACKNOWLEDGED" | "INVESTIGATING" | "ESCALATED" | "RESOLVED" | "CLOSED";
        readonly VersionedCommand: {
            /** @description Optimistic case version from the most recent read. */
            readonly version: number;
        };
        readonly CaseAssignment: components["schemas"]["VersionedCommand"] & {
            /** Format: uuid */
            readonly assigneeUserId: string;
        };
        readonly CaseNoteCommand: components["schemas"]["VersionedCommand"] & {
            readonly body: string;
        };
        readonly SummaryCommand: components["schemas"]["VersionedCommand"] & {
            readonly summary: string;
        };
        readonly DispositionCommand: components["schemas"]["VersionedCommand"] & {
            readonly disposition: string;
        };
        readonly ResolveCaseCommand: components["schemas"]["VersionedCommand"] & {
            /** @enum {string} */
            readonly resolutionCode: "VERIFIED_NORMAL_ACTIVITY" | "DATA_QUALITY_CONFIRMED" | "ESCALATED_TO_OPERATIONS" | "NO_FURTHER_REVIEW_REQUIRED";
            readonly resolutionSummary: string;
        };
        readonly Case: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly outletId: string;
            /** Format: uuid */
            readonly providerId: string | null;
            readonly state: components["schemas"]["CaseState"];
            readonly version: number;
            /** Format: uuid */
            readonly ownerUserId: string | null;
            readonly resolutionCode: string | null;
            readonly resolutionSummary: string | null;
            /** Format: uuid */
            readonly createdBy: string;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
            /** Format: date-time */
            readonly resolvedAt: string | null;
            /** Format: date-time */
            readonly closedAt: string | null;
        };
        readonly CaseTimeline: {
            /** Format: uuid */
            readonly caseId: string;
            readonly events: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly notes: readonly {
                readonly [key: string]: unknown;
            }[];
            readonly auditEvents: readonly {
                readonly [key: string]: unknown;
            }[];
        };
        readonly AlertCaseResponse: {
            readonly case: components["schemas"]["Case"];
            /** Format: uuid */
            readonly alertId: string;
        };
        readonly Alert: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly outletId: string;
            /**
             * Format: uuid
             * @description Null for redacted shared-cash and outlet-wide review alerts.
             */
            readonly providerId: string | null;
            /** @enum {string|null} */
            readonly resource: "shared_cash" | "provider_efloat" | null;
            readonly type: components["schemas"]["AlertType"];
            /** @enum {string} */
            readonly severity: "low" | "moderate" | "high" | "critical";
            /** @enum {string} */
            readonly status: "open" | "acknowledged" | "assigned" | "case_created" | "resolved";
            readonly active: boolean;
            /** Format: date-time */
            readonly episodeStartedAt: string;
            /** Format: date-time */
            readonly lastObservedAt: string;
            readonly occurrenceCount: number;
            readonly message: {
                /** @enum {string} */
                readonly key: "alerts.provider_emoney_pressure.review" | "alerts.shared_cash_pressure.review" | "alerts.unusual_activity_review.review" | "alerts.data_quality_issue.review" | "alerts.combined_review.review";
                /** @description Localize using English/Bengali client message catalogs; never infer a financial action. */
                readonly params: {
                    readonly [key: string]: unknown;
                };
            };
            readonly evidence: {
                readonly [key: string]: unknown;
            };
            /** @enum {string} */
            readonly dataQuality: "healthy" | "degraded" | "unreliable";
            readonly modelConfidence: number;
            /** Format: uuid */
            readonly ownerUserId: string | null;
            /** Format: date-time */
            readonly acknowledgedAt: string | null;
            /** Format: uuid */
            readonly acknowledgedBy: string | null;
        };
        readonly AlertDetail: components["schemas"]["Alert"] & {
            readonly evidenceSnapshots: readonly {
                /** @enum {string} */
                readonly kind: "forecast" | "anomaly_signal" | "data_quality_incident" | "correlation";
                /** Format: date-time */
                readonly observedAt: string;
                readonly snapshot: {
                    readonly [key: string]: unknown;
                };
            }[];
        };
        readonly AlertAssignment: {
            /**
             * Format: uuid
             * @description Must be a recipient derived from alert routing.
             */
            readonly assigneeUserId: string;
        };
        readonly FeedHealthPage: {
            readonly items: readonly {
                /** Format: uuid */
                readonly providerId: string;
                readonly sequence: string;
                /** Format: date-time */
                readonly receivedAt: string;
                /** @enum {string} */
                readonly qualityStatus: "healthy" | "degraded";
                /** @enum {string} */
                readonly dataQuality: "healthy" | "degraded" | "unreliable";
                readonly activeIncidentCount: number;
                /** Format: date-time */
                readonly latestIncidentAt: string | null;
            }[];
            /** Format: uuid */
            readonly nextCursor: string | null;
        };
        readonly DataQualityIncidentPage: {
            readonly items: readonly {
                /** Format: uuid */
                readonly id: string;
                /** Format: uuid */
                readonly providerId: string | null;
                /** Format: uuid */
                readonly outletId: string | null;
                readonly category: string;
                readonly details: {
                    readonly [key: string]: unknown;
                };
                /** Format: date-time */
                readonly detectedAt: string;
                /** Format: date-time */
                readonly resolvedAt: string | null;
            }[];
            /** Format: uuid */
            readonly nextCursor: string | null;
        };
        readonly ManagementReadiness: {
            /** Format: date-time */
            readonly generatedAt: string;
            readonly providersReporting: number;
            readonly providersDegraded: number;
            readonly providersUnreliable: number;
            readonly activeIncidentCount: number;
            readonly unresolvedOutletCount: number;
            /** Format: date-time */
            readonly latestFeedReceivedAt: string | null;
        };
        readonly StandardError: {
            readonly code: string;
            readonly message: string;
            readonly fieldErrors: {
                readonly [key: string]: readonly string[];
            };
            readonly correlationId: string;
        };
    };
    responses: {
        /** @description Standard safe error response. Authentication failures use `MISSING_ACCESS_TOKEN` or `INVALID_ACCESS_TOKEN`; malformed filters use a route-specific `INVALID_*_QUERY`; unauthorized scope is represented without disclosing whether a guessed resource exists. */
        readonly StandardError: {
            headers: {
                readonly "X-Correlation-Id": components["headers"]["CorrelationId"];
                readonly [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "MISSING_ACCESS_TOKEN",
                 *       "message": "A Supabase bearer access token is required.",
                 *       "fieldErrors": {},
                 *       "correlationId": "00000000-0000-4000-8000-000000000001"
                 *     }
                 */
                readonly "application/json": components["schemas"]["StandardError"];
            };
        };
    };
    parameters: {
        readonly PageLimit: number;
        readonly PageCursor: string;
        /** @description Narrowing filter only; it cannot expand verified provider scope. */
        readonly ProviderFilter: string;
        /** @description Narrowing filter only; it cannot expand verified outlet scope. */
        readonly OutletFilter: string;
        readonly CaseId: string;
        readonly AlertId: string;
        /** @description Required replay-safe workflow mutation key. */
        readonly IdempotencyKey: string;
        readonly OutletId: string;
        /** @description Provider-scoped credential. Never send this from a browser client. */
        readonly ProviderIngestKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Request correlation identifier. Client-supplied valid UUID values are echoed. */
        readonly CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly getLiveHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description API is live */
            readonly 200: {
                headers: {
                    readonly "X-Correlation-Id": components["headers"]["CorrelationId"];
                    readonly [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "service": "prohori-api",
                     *       "status": "ok"
                     *     }
                     */
                    readonly "application/json": components["schemas"]["LiveHealthResponse"];
                };
            };
            readonly 500: components["responses"]["StandardError"];
        };
    };
    readonly getCurrentUser: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Authenticated profile. Implemented in Step 3. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CurrentUser"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 503: components["responses"]["StandardError"];
        };
    };
    readonly listProviders: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Providers in caller scope */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Provider"][];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 503: components["responses"]["StandardError"];
        };
    };
    readonly listAreas: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Areas in caller scope */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Area"][];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 503: components["responses"]["StandardError"];
        };
    };
    readonly listOutlets: {
        readonly parameters: {
            readonly query?: {
                /** @example DHAKA_NORTH */
                readonly areaCode?: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Outlets in caller scope */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Outlet"][];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 503: components["responses"]["StandardError"];
        };
    };
    readonly ingestProviderBatch: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Provider-scoped credential. Never send this from a browser client. */
                readonly "X-Provider-Ingest-Key": components["parameters"]["ProviderIngestKey"];
            };
            readonly path: {
                readonly provider: components["schemas"]["ProviderCode"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                /**
                 * @example {
                 *       "sequence": 1,
                 *       "sourceAt": "2026-01-01T08:00:00.000Z",
                 *       "receivedAt": "2026-01-01T08:00:30.000Z",
                 *       "events": [],
                 *       "snapshots": [],
                 *       "checksum": "8f3f6d7407c38bfdfb9c0f2e0cfc6a6ab7fbc8246f4e6b7424f02014d0cbb714"
                 *     }
                 */
                readonly "application/json": components["schemas"]["IngestionBatch"];
            };
        };
        readonly responses: {
            /** @description Receipt and data-quality result */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["IngestionReceipt"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 409: components["responses"]["StandardError"];
            readonly 503: components["responses"]["StandardError"];
        };
    };
    readonly getOutletHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["OutletId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Scoped outlet health */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OutletHealth"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly getOutletBalances: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["OutletId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Authorized resource positions */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OutletBalances"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly getOutletForecasts: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["OutletId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Persisted forecast run */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ForecastRun"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly listOutletAnomalies: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["OutletId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Authorized unusual-activity review signals */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "80000000-0000-4000-8000-000000000001",
                     *         "message": "Unusual activity requires review.",
                     *         "detectorType": "repeated_amount",
                     *         "detectorVersion": "1.0.0",
                     *         "observedValue": 4,
                     *         "baselineValue": 0,
                     *         "threshold": 3,
                     *         "score": 1,
                     *         "provider": {
                     *           "id": "10000000-0000-4000-8000-000000000002",
                     *           "code": "PROVIDER_B",
                     *           "name": "Provider B",
                     *           "status": "ACTIVE"
                     *         },
                     *         "sourceTransactionIds": [
                     *           "90000000-0000-4000-8000-000000000001"
                     *         ],
                     *         "evidenceWindow": {
                     *           "start": "2026-01-01T07:00:00.000Z",
                     *           "end": "2026-01-01T08:00:00.000Z"
                     *         },
                     *         "possibleBenignExplanation": "A scheduled campaign or common denomination may produce repeated amounts; review the event context.",
                     *         "modelConfidence": 0.5,
                     *         "dataQuality": "healthy",
                     *         "correlation": {
                     *           "score": 1,
                     *           "threshold": 0.75,
                     *           "context": "Shared-cash liquidity pressure and unusual activity overlap in the same deterministic evidence window. This correlation does not establish causation."
                     *         }
                     *       }
                     *     ]
                     */
                    readonly "application/json": readonly components["schemas"]["AnomalySignal"][];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly getOutletDataQuality: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["OutletId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Derived quality and underlying active incidents */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OutletDataQuality"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly listOutletTransactions: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly cursor?: string;
            };
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["OutletId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Authorized transaction page */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TransactionPage"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly resetSimulation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Scenario state reset */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 403: components["responses"]["StandardError"];
        };
    };
    readonly startSimulation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                /**
                 * @example {
                 *       "scenario": "A"
                 *     }
                 */
                readonly "application/json": components["schemas"]["SimulationCommand"];
            };
        };
        readonly responses: {
            /** @description Scenario started */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 403: components["responses"]["StandardError"];
        };
    };
    readonly stepSimulation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SimulationCommand"];
            };
        };
        readonly responses: {
            /** @description Next scenario batch applied */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 403: components["responses"]["StandardError"];
        };
    };
    readonly listAlerts: {
        readonly parameters: {
            readonly query?: {
                readonly active?: boolean;
                readonly outletId?: string;
                readonly type?: components["schemas"]["AlertType"];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Scoped alert episodes */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "90000000-0000-4000-8000-000000000001",
                     *         "outletId": "30000000-0000-4000-8000-000000000001",
                     *         "providerId": "10000000-0000-4000-8000-000000000001",
                     *         "resource": "provider_efloat",
                     *         "type": "provider_emoney_pressure",
                     *         "severity": "high",
                     *         "status": "open",
                     *         "active": true,
                     *         "episodeStartedAt": "2026-01-01T12:00:00.000Z",
                     *         "lastObservedAt": "2026-01-01T12:00:00.000Z",
                     *         "occurrenceCount": 1,
                     *         "message": {
                     *           "key": "alerts.provider_emoney_pressure.review",
                     *           "params": {
                     *             "severity": "high"
                     *           }
                     *         },
                     *         "evidence": {
                     *           "forecastRunId": "70000000-0000-4000-8000-000000000001"
                     *         },
                     *         "dataQuality": "healthy",
                     *         "modelConfidence": 0.8,
                     *         "ownerUserId": null,
                     *         "acknowledgedAt": null,
                     *         "acknowledgedBy": null
                     *       }
                     *     ]
                     */
                    readonly "application/json": readonly components["schemas"]["Alert"][];
                };
            };
            readonly 401: components["responses"]["StandardError"];
        };
    };
    readonly getAlert: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["AlertId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Scoped alert detail */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AlertDetail"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly acknowledgeAlert: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["AlertId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Acknowledged alert */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Alert"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly assignAlert: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["AlertId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                /**
                 * @example {
                 *       "assigneeUserId": "40000000-0000-4000-8000-000000000002"
                 *     }
                 */
                readonly "application/json": components["schemas"]["AlertAssignment"];
            };
        };
        readonly responses: {
            /** @description Assigned alert */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Alert"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly createAlertCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["AlertId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Case created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AlertCaseResponse"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly listCases: {
        readonly parameters: {
            readonly query?: {
                readonly state?: components["schemas"]["CaseState"];
                readonly outletId?: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Scoped cases */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Case"][];
                };
            };
            readonly 401: components["responses"]["StandardError"];
        };
    };
    readonly getCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Scoped case */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Case"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly getCaseTimeline: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Append-only case timeline */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CaseTimeline"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly acknowledgeCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                /**
                 * @example {
                 *       "version": 1
                 *     }
                 */
                readonly "application/json": components["schemas"]["VersionedCommand"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Case"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly assignCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                /**
                 * @example {
                 *       "version": 1,
                 *       "assigneeUserId": "40000000-0000-4000-8000-000000000002"
                 *     }
                 */
                readonly "application/json": components["schemas"]["CaseAssignment"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Case"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly addCaseNote: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                /**
                 * @example {
                 *       "version": 2,
                 *       "body": "Verification requested from the outlet."
                 *     }
                 */
                readonly "application/json": components["schemas"]["CaseNoteCommand"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Case"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly requestCaseVerification: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SummaryCommand"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly escalateCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["VersionedCommand"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly recordCaseDisposition: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["DispositionCommand"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly resolveCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                /**
                 * @example {
                 *       "version": 4,
                 *       "resolutionCode": "VERIFIED_NORMAL_ACTIVITY",
                 *       "resolutionSummary": "Review completed; no financial action was taken."
                 *     }
                 */
                readonly "application/json": components["schemas"]["ResolveCaseCommand"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly closeCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["VersionedCommand"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly reopenCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Required replay-safe workflow mutation key. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            readonly path: {
                readonly id: components["parameters"]["CaseId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["VersionedCommand"];
            };
        };
        readonly responses: {
            /** @description Updated case */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
            readonly 404: components["responses"]["StandardError"];
        };
    };
    readonly listFeedHealth: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: components["parameters"]["PageLimit"];
                readonly cursor?: components["parameters"]["PageCursor"];
                /** @description Narrowing filter only; it cannot expand verified provider scope. */
                readonly providerId?: components["parameters"]["ProviderFilter"];
                /** @description Narrowing filter only; it cannot expand verified outlet scope. */
                readonly outletId?: components["parameters"]["OutletFilter"];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Scoped feed-health page */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "providerId": "10000000-0000-4000-8000-000000000001",
                     *           "sequence": "14",
                     *           "receivedAt": "2026-01-01T12:00:30.000Z",
                     *           "qualityStatus": "degraded",
                     *           "dataQuality": "degraded",
                     *           "activeIncidentCount": 1,
                     *           "latestIncidentAt": "2026-01-01T12:00:30.000Z"
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    readonly "application/json": components["schemas"]["FeedHealthPage"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
        };
    };
    readonly listDataQualityIncidents: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: components["parameters"]["PageLimit"];
                readonly cursor?: components["parameters"]["PageCursor"];
                /** @description Narrowing filter only; it cannot expand verified provider scope. */
                readonly providerId?: components["parameters"]["ProviderFilter"];
                /** @description Narrowing filter only; it cannot expand verified outlet scope. */
                readonly outletId?: components["parameters"]["OutletFilter"];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Scoped data-quality incident page */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "50000000-0000-4000-8000-000000000001",
                     *           "providerId": "10000000-0000-4000-8000-000000000001",
                     *           "outletId": "30000000-0000-4000-8000-000000000001",
                     *           "category": "FRESHNESS_LAG",
                     *           "details": {
                     *             "lagMinutes": 20
                     *           },
                     *           "detectedAt": "2026-01-01T12:00:30.000Z",
                     *           "resolvedAt": null
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    readonly "application/json": components["schemas"]["DataQualityIncidentPage"];
                };
            };
            readonly 400: components["responses"]["StandardError"];
            readonly 401: components["responses"]["StandardError"];
        };
    };
    readonly getManagementReadiness: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Redacted management aggregate */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "generatedAt": "2026-01-01T12:00:30.000Z",
                     *       "providersReporting": 3,
                     *       "providersDegraded": 1,
                     *       "providersUnreliable": 0,
                     *       "activeIncidentCount": 2,
                     *       "unresolvedOutletCount": 1,
                     *       "latestFeedReceivedAt": "2026-01-01T12:00:30.000Z"
                     *     }
                     */
                    readonly "application/json": components["schemas"]["ManagementReadiness"];
                };
            };
            readonly 401: components["responses"]["StandardError"];
            readonly 403: components["responses"]["StandardError"];
        };
    };
}
